### ISSUE TITLE
Formatter is broken

### ISSUE THREAD

**Issue by ghost** [keyhr/vscode-42-c-format#10]
While working on a file it randomly stopped working and I got this:

"Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mpoplow/c_formatter_42/c_formatter_42/__main__.py", line 63, in <module>
    main()
  File "/Users/mpoplow/c_formatter_42/c_formatter_42/__main__.py", line 43, in main
    print(run_all(content), end="")
  File "/Users/mpoplow/c_formatter_42/c_formatter_42/run.py", line 29, in run_all
    content = clang_format(content)
  File "/Users/mpoplow/c_formatter_42/c_formatter_42/formatters/clang_format.py", line 74, in clang_format
    raise RuntimeError(f"clang-format error: {err.decode()}")
RuntimeError: clang-format error: Configuration file(s) do(es) not support Objective-C: /Users/mpoplow/prj/getnextline_WORK/.clang-format

42-c-format: Please read README and check requirements."

Idk, I tried restarting, reinstalling of both the extension and VS-Code, restarting and switching the computer and much more. I don't know how to fix it.

**Comment by keyhr** [comment]
> RuntimeError: clang-format error: Configuration file(s) do(es) not support Objective-C: /Users/mpoplow/prj/getnextline_WORK/.clang-format

It seems there might be an issue with your clang-format configuration file (at `/Users/mpoplow/prj/getnextline_WORK/.clang-format`). Can you check it?
