### ISSUE TITLE
Problem with getting the formatter to work on windows

### ISSUE THREAD

**Issue by baschni** [keyhr/vscode-42-c-format#6]
Hi,

i installed the pip packet and added the configuration line to my settings.json.

When I then run "Format document" nothings happens, but I can show the output:

`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Programs\Python\Python312\Lib\site-packages\c_formatter_42\__main__.py", line 64, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Programs\Python\Python312\Lib\site-packages\c_formatter_42\__main__.py", line 43, in main
    print(run_all(content), end="")
          ^^^^^^^^^^^^^^^^
  File "C:\Programs\Python\Python312\Lib\site-packages\c_formatter_42\run.py", line 29, in run_all
    content = clang_format(content)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Python\Python312\Lib\site-packages\c_formatter_42\formatters\clang_format.py", line 64, in clang_format
    with _config_context():
  File "C:\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Programs\Python\Python312\Lib\site-packages\c_formatter_42\formatters\clang_format.py", line 33, in _config_context
    CONFIG_FILENAME.symlink_to(config_path)
  File "C:\Programs\Python\Python312\Lib\pathlib.py", line 1386, in symlink_to
    os.symlink(target, self, target_is_directory)
OSError: [WinError 1314] Dem Client fehlt ein erforderliches Recht: 'C:\\Programs\\Python\\Python312\\Lib\\site-packages\\c_formatter_42\\data\\.clang-format' -> '.clang-format'

42-c-format: Please read README and check requirements.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Programs\Python\Python312\Lib\site-packages\c_formatter_42\__main__.py", line 64, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Programs\Python\Python312\Lib\site-packages\c_formatter_42\__main__.py", line 43, in main
    print(run_all(content), end="")
          ^^^^^^^^^^^^^^^^
  File "C:\Programs\Python\Python312\Lib\site-packages\c_formatter_42\run.py", line 29, in run_all
    content = clang_format(content)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programs\Python\Python312\Lib\site-packages\c_formatter_42\formatters\clang_format.py", line 64, in clang_format
    with _config_context():
  File "C:\Programs\Python\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Programs\Python\Python312\Lib\site-packages\c_formatter_42\formatters\clang_format.py", line 33, in _config_context
    CONFIG_FILENAME.symlink_to(config_path)
  File "C:\Programs\Python\Python312\Lib\pathlib.py", line 1386, in symlink_to
    os.symlink(target, self, target_is_directory)
OSError: [WinError 1314] Dem Client fehlt ein erforderliches Recht: 'C:\\Programs\\Python\\Python312\\Lib\\site-packages\\c_formatter_42\\data\\.clang-format' -> '.clang-format'

42-c-format: Please read README and check requirements.`

It seems like a problem with sym linking. What can I do to make it work?

**Comment by keyhr** [comment]
Does this issue also occur when running c_formatter_42 standalone? You can try running `python3 -m c_formatter_42 < [your file name].c` to check it.
